# Site settings
title: Paul Hanakata
email: paul.hanakata[at]gmail.com
department: Physics Department, Boston University
address1: 590 Commonwealth Avenue
address2: Boston, MA 02215
description: > # this means to ignore newlines until "baseurl:"
  I study electronic and mechanical properties of 2D materials beyond graphene using density functional theory methods.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://phanakata.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  phanakata
#google_play: 'GDGX'
#google_plus_com: '109485346959707049693'  # Community link
#google_plus_per: '+GDGManagua'  #Personal link
#facebook_app_id: 12345
linkedin_id: paul-hanakata-b74785156
researchgate_id: Paul_Hanakata

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

plugins:
  - jekyll-seo-tag

more_vert:
  #option1:
  #  name: Cool Option 1
  #  link: www.myawesomelink.com
  #option2:
  #  name: Cool Option 2
  #  link: www.myawesomelink.com
  #option3:
  #  name: Cool Option 3
  #  link: www.myawesomelink.com

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
# Google Analytics
google_analytics: UA-123709154-1

